-- TD/TP
-- PRODUIT, CATEGORIE, MAGASIN, LIEU,VENTE, BAREME.

-- DROP all tables
DROP TABLE Vente PURGE;
DROP TABLE Produit PURGE;
DROP TABLE Categorie PURGE;
DROP TABLE Magasin PURGE;
DROP TABLE Lieu PURGE;
