CREATE TABLE Villes (
  NomV VARCHAR(20) PRIMARY KEY
);

CREATE TABLE Bus (
  NumB NUMERIC(3) PRIMARY KEY,
  CapaciteB NUMERIC(3) NOT NULL
);

CREATE TABLE Trajets (
  NumT NUMERIC(3) PRIMARY KEY,
  NumB NUMERIC(3) REFERENCES Bus(NumB),
);

CREATE TABLE Etapes (
  NumT NUMERIC(3) REFERENCES Trajets(NumT),
  NomV VARCHAR(20) REFERENCES Villes(NomV),
  DateA DATE NOT NULL,
  DateD DATE NOT NULL,
  PRIMARY KEY (NumT, NomV),
  CONSTRAINT C3 CHECK ((DateD - DateA)*24*60 >= 5)
);

CREATE TABLE Tarifs (
  VilleD VARCHAR(30) REFERENCES Villes(NomV),
  VilleA VARCHAR(30) REFERENCES Villes(NomV),
  Prix NUMERIC(5,2) NOT NULL,
  PRIMARY KEY (VilleD, VilleA)
);

CREATE TABLE Clients (
  NumC NUMERIC(5) PRIMARY KEY,
  NomC VARCHAR(20) NOT NULL,
  AdresseC VARCHAR(50) NOT NULL
);

CREATE TABLE Reservations (
  NumR NUMERIC(5) PRIMARY KEY,
  NumC NUMERIC(5) REFERENCES Clients(NumC),
  NumT NUMERIC(3),
  VilleD VARCHAR(30),
  VilleA VARCHAR(30),
  Nbplaces NUMERIC(3) DEFAULT 1 NOT NULL,
  FOREIGN KEY (NumT, VilleD) REFERENCES Etapes(NumT, NomV),
  FOREIGN KEY (NumT, VilleA) REFERENCES Etapes(NumT, NomV),
  FOREIGN KEY (VilleD, VilleA) REFERENCES Tarifs(VilleD, VilleA),
  CONSTRAINT C1 CHECK (Nbplaces > 0),
  CONSTRAINT C2 CHECK (VilleD <> VilleA)
);
